export enum Route {
    DATE_PICKER = 'DATE PICKER',
    DEBT = 'DEBT',
    ERROR = 'ERROR',
    EXPENSE = 'EXPENSE',
    EXPENSES = 'EXPENSES',
    FIXED_CATEGORIES = 'FIXED',
    HOME = 'HOME',
    INCOME = 'INCOME',
    INFORMATION = 'INFORMATION',
    LOADING = 'LOADING',
    LOGIN = 'LOGIN',
    SAVINGS = 'SAVINGS',
    SETTINGS = 'SETTINGS',
    VARIABLE_CATEGORIES = 'VARIABLE',
    VARIABLE_CATEGORY = 'VARIABLE CATEGORY',
    ROOT_STACK = 'ROOT STACK',
    DRAWER = 'DRAWER'
}
