require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'
target 'EasyBudget' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'GoogleSignIn', '~> 5.0.0'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  post_install do |installer|
    flipper_post_install(installer)
  end
end
